name: Deploy Dev Lambda Invoke Gemini

env:
  PROJECT_NAME: genai
  ENVIRONMENT: ${{ github.event.inputs.environment }}
  AWS_REGION: us-east-1
  LAMBDA_CONTAINER_DIR: lambda_invoke_gemini

on:
  push:
    branches: [develop]
    paths:
      - "functions/invoke_gemini/**"
      - "containers/lambda_invoke_gemini/**"
      - ".github/workflows/deploy-dev-lambda-invoke-gemini.yaml"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        options:
          - dev

jobs:
  deploy:
    if: |
      github.event.sender.type != 'Bot'
      && !startsWith(github.head_ref, 'release')
      && !startsWith(github.head_ref, 'doc')
    name: Run Deploy Dev Lambda Invoke Gemini
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEV_LAMBDA_DEPLOY_ROLE  }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set ECR env and mask values
        run: |
          echo "::add-mask::${{ steps.login-ecr.outputs.registry }}"

          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=${{ env.PROJECT_NAME }}/${{ env.ENVIRONMENT }}/${{ env.LAMBDA_CONTAINER_DIR }}:latest" >> $GITHUB_ENV
          echo "ECR_IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.PROJECT_NAME }}/${{ env.ENVIRONMENT }}/${{ env.LAMBDA_CONTAINER_DIR }}:latest" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build and push container image
        run: |
          docker buildx build --platform linux/amd64 --no-cache -t ${{ env.ECR_IMAGE_URI }} -f containers/${{ env.LAMBDA_CONTAINER_DIR }}/Dockerfile .
          docker push ${{ env.ECR_IMAGE_URI }}

      - name: Update Lambda Function (silent)
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}-invoke-gemini \
            --image-uri ${{ env.ECR_IMAGE_URI }} \
            >/dev/null 2>&1
